### ISSUE TITLE
Fix dark mode

### ISSUE THREAD

**Issue by ddikman** [ddikman/genre-substantif#11]
If the client has dark mode enabled, the search box doesn't appear very good.

Also, it could be an idea to actually implement dark mode.

![image](https://github.com/ddikman/genre-substantif/assets/8461739/5d51a2f7-67b2-4a49-803b-dc4e6ee9923b)

**Comment by jojommeke** [comment]
you should add this line in css:
`#word[data-v-4ba6107b] {
  display: block;
  background: #FFF;
}`

**Comment by ddikman** [comment]
@jojommeke thank you, just the kick in the butt I needed to actually address this :)

There was an issue not just on the input but on some buttons as well so I addressed it like this #13
